swagger: "2.0"
info:
  version: "2.0.0"
  title: "NDV Service API"
host: "localhost:8080"
basePath: "/"
tags:
  - name: "Partners"
    description: "partners"
  - name: "partners"
    description: "partner endpoints"

paths:
  /api/partners:
    get:
      tags:
        - "Partners"
      summary: "Get all partners"
      description: ""
      operationId: "GetAllPartners"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationArea"
        "404":
          description: "Area not found"
          schema:
            type: object
            properties:
              messages:
                type: string
                format: nullable
                example: null
              code:
                type: string
                example: NOT_FOUND
        "500":
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ApiError"